CREATE SEQUENCE groupSequence AS INTEGER;

CREATE TABLE productGroup (
  id INT NOT NULL,
  name varchar(50) NOT NULL,
  groupType varchar(30) NULL,
  CONSTRAINT pk_productGroup PRIMARY KEY (id)
);

CREATE TABLE tag (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE product (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(100) NOT NULL,
  idGroup INT NOT NULL,
  CONSTRAINT pk_product PRIMARY KEY (id),
  CONSTRAINT fk_product_group FOREIGN KEY (idGroup)
  REFERENCES productGroup (id)
);

CREATE TABLE productTag (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  idProduct INT NOT NULL,
  idTag INT NOT NULL,
  CONSTRAINT pk_productTag PRIMARY KEY (id),
  CONSTRAINT fk_productTag_tag FOREIGN KEY (idTag)
  REFERENCES tag (id),
  CONSTRAINT fk_productTag_product FOREIGN KEY (idProduct)
  REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE user (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  login VARCHAR(80) NOT NULL,
  firstName VARCHAR(120) NULL,
  lastName VARCHAR(120) NULL,
  birthDate DATE NULL,
  state SMALLINT NOT NULL,
  type VARCHAR(15) NOT NULL,
  employeeNumber VARCHAR(5),
  companyName VARCHAR(80),
  companyIdNumber VARCHAR(11),
  CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE userProduct (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  idProduct INT NOT NULL,
  idUser INT NOT NULL,
  CONSTRAINT pk_userProduct PRIMARY KEY (id),
  CONSTRAINT fk_userProduct_tag FOREIGN KEY (idProduct)
  REFERENCES product (id) ON DELETE CASCADE,
  CONSTRAINT fk_userProduct_user FOREIGN KEY (idUser)
  REFERENCES user (id) ON DELETE CASCADE
);